# Frequency Counter Project - Nandland Go Board
PROJ = frequency_counter
TOP = frequency_counter_top
SRCS = frequency_counter_top.v freq_counter.v uart_tx.v test_freq_gen.v

include ../../../config/common.mk
