// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input v9577cd,
 input vebf162,
 input vb33be2,
 input v81a7df,
 output v997b6b,
 output ve3f8af,
 output v29296c,
 output vb7dedc
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v9577cd;
 assign v997b6b = w0;
 assign w1 = vebf162;
 assign ve3f8af = w1;
 assign w2 = vb33be2;
 assign v29296c = w2;
 assign w3 = v81a7df;
 assign vb7dedc = w3;
endmodule

